name: Coverage compuation CI

on:
  pull_request:
    branches: [ "main", "developement" ]

jobs:
  build:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - name: Run tests
      run: npm test -- --coverage --coverageReporters json-summary | tee ./coverage.txt

    - name: Jest Coverage Comment
      uses: MishaKav/jest-coverage-comment@main
      id: coverage
      with:
        report-only-changed-files: true
        coverage-path: ./coverage.txt
    - run: |
        echo steps.coverage.outputs.lines
